### PR TITLE
support : AnsiFormatter.disabled = true

### PR DESCRIPTION
**Pull request by jeremyz**
there it is, I'm not a scala man ... hope that the way i did that is acceptable.
referencing issue : #2

### CODE REVIEW

**Comment by backuitist** [comment]
You understand that this is happening at compile-time? So once compiled with the flag set to true you won't see any ansi formatting, ever.
What is your use-case?

**Comment by jeremyz** [comment]
Yes I do.
I've been working on improving the output of that : https://github.com/sellmerfud/awakening
But for sure, most of the users will be windows guys with no terminal with ansi capabilities, so to have my patch upstreamed, it must be disabled by default.

**Comment by backuitist** [comment]
Ok, I see. I'm not too fan of mutating the `AnsiFormatter` object. That makes the library a runtime dependency for one and isn't specially elegant. I would rather do this:
- have an environment variable
- that could disable it completely
- or even better insert platform specific switch - so if the environment variable is set to `ansi-windows-support` (this could be the default) then calls to `ansi"%blueX"` would translate to `if (platform.isWindow) "X" else "blue X"`

**Comment by jeremyz** [comment]
I don't get that : "That makes the library a runtime dependency", it can't.

to keep `AnsiFormatter` immutable, what if I replace `var AnsiFormatter.disabled` with:

`val isWindows = Option(System.getProperty("os.name")).getOrElse("").contains("indows")`
`val forceAnsi = !sys.env.get("ansi-windows-support").getOrElse("-").equals("-")`
`val disabled = (!sys.env.get("ansi-formatter-disabled").getOrElse("-").equals("-") || (isWindows && !forceAnsi))`

so it will be by default disabled on windows, forced with "ansi-windows-support".
on every platform disabled with "ansi-formatter-disabled".

I don't know how to write a test suite for that though, it seems that env is immutable in scala.

**Comment by jeremyz** [comment]
Hello, ping ?

**Comment by wajda** [comment]
I think the problem here is (as @backuitist pointed out) that those env variable are read at the compile time, while the intention is (as I understand it) to have the check being done at runtime.

I have created a PR #5 that uses a different approach. Could you please take a look?

**Comment by jeremyz** [comment]
> I think the problem here is (as @backuitist pointed out) that those env variable are read at the compile time, while the intention is (as I understand it) to have the check being done at runtime.
> 
> I have created a PR #5 that uses a different approach. Could you please take a look?

System.getProperty(…) is not evaluated at compile time, neither is sys.env.get(…)
whatever, I'll gladly have a look at your PR tomorrow.

**Comment by backuitist** [comment]
Sorry @jeremyz for the (extremely) late answer, missed the notifications...
I have merged @wajda PR, but I think we could combine the two approaches; I will create another PR for that.

**Comment by backuitist** [comment]
See there @jeremyz https://github.com/backuity/ansi-interpolator/pull/6

**Pull request closed without merging**
